insert into book (id, title, authors, status) values (1, 'First book', 'Jan Kowalski', 'FREE');
insert into book (id, title, authors, status) values (2, 'Second book', 'Zbigniew Nowak', 'FREE');
insert into book (id, title, authors, status) values (3, 'Third book', 'Janusz Jankowski', 'FREE');
insert into book (id, title, authors, status) values (4, 'Fourth book', 'Kacper Ossoliński', 'FREE');
insert into book (id, title, authors, status) values (5, 'Fifth book', 'Krystyna Czubówna', 'MISSING');
insert into book (id, title, authors, status) values (6, 'Sixth book', 'Jan Kowalski', 'FREE');
insert into book (id, title, authors, status) values (7, 'Seventh book', 'Zbigniew Nowak', 'FREE');
insert into book (id, title, authors, status) values (8, 'Eight book', 'Janusz Jankowski', 'FREE');
insert into book (id, title, authors, status) values (9, 'Ninth book', 'Kacper Ossoliński', 'FREE');
insert into book (id, title, authors, status) values (10, 'Ten book', 'Krystyna Czubówna', 'MISSING');
insert into book (id, title, authors, status) values (11, 'First book', 'Krystyna Czubówna', 'FREE');
insert into book (id, title, authors, status) values (12, 'Second book', 'Zbigniew Nowak', 'FREE');
insert into book (id, title, authors, status) values (13, 'Third book', 'Janusz Jankowski', 'FREE');
insert into book (id, title, authors, status) values (14, 'Starter kit book', 'Kacper Ossoliński', 'FREE');
insert into book (id, title, authors, status) values (15, 'Z kamerą wśród programistów', 'Krystyna Czubówna', 'MISSING');
insert into book (id, title, authors, status) values (16, 'First book', 'Jan Kowalski', 'FREE');
insert into book (id, title, authors, status) values (17, 'Second book', 'Zbigniew Nowak', 'FREE');
insert into book (id, title, authors, status) values (18, 'Third book', 'Janusz Jankowski', 'FREE');
insert into book (id, title, authors, status) values (19, 'Starter kit book', 'Kacper Ossoliński', 'FREE');
insert into book (id, title, authors, status) values (20, 'Z kamerą wśród programistów', 'Krystyna Czubówna', 'MISSING');

insert into user (id, user_name, password) values (1, 'admin', 'admin');
insert into user (id, user_name, password) values (2, 'user', 'user');